name: Gatsby CI/CD

# Run the workflow on push to the main branch and pull requests
on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Ensure you're using the correct version

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Lint
        run: npm run lint
        # Use your linter command (e.g., `npm run lint` <span class='kc-markdown-code-copy'></span> or `eslint .` <span class='kc-markdown-code-copy'></span>)

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint # Ensure linting passes before testing
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Run Tests
        run: npm test
        # Use your testing command (e.g., `npm test` <span class='kc-markdown-code-copy'></span> or `jest` <span class='kc-markdown-code-copy'></span>)

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: test # Ensure tests pass before deploying
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build Gatsby
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # The directory where the built files are located
